// Generated by scripts/embed.mjs; do not edit.
#pragma once
namespace webgpu_fft::detail {
inline constexpr char arithmetic[] = R"WGSL(
fn rnd(v:f32,s:u32)->f32 {
    atomicStore(&rounding[s],bitcast<u32>(v));
    return bitcast<f32>(atomicLoad(&rounding[s]));
}
fn norm(a:vec2f,s:u32)->vec2f {
    let h=rnd(a.x+a.y,s);let v=rnd(h-a.x,s);
    return vec2f(h,rnd(a.y-v,s));
}
fn add(a:vec2f,b:vec2f,s:u32)->vec2f {
    let h=rnd(a.x+b.x,s);let bv=rnd(h-a.x,s);let av=rnd(h-bv,s);
    let ae=rnd(a.x-av,s);let be=rnd(b.x-bv,s);
    let e=rnd(ae+be,s);let l=rnd(e+a.y,s);
    return norm(vec2f(h,rnd(l+b.y,s)),s);
}
fn mul(a:vec2f,b:vec2f,s:u32)->vec2f {
    let h=rnd(a.x*b.x,s);let e=rnd(fma(a.x,b.x,-h),s);
    let c0=rnd(a.x*b.y,s);let c1=rnd(a.y*b.x,s);
    return norm(vec2f(h,rnd(rnd(e+c0,s)+c1,s)),s);
}
)WGSL";
inline constexpr char paired[] = R"WGSL(
fn cadd(a:vec4f,b:vec4f,s:u32)->vec4f {
    let r=add(a.xz,b.xz,s);let i=add(a.yw,b.yw,s);
    return vec4f(r.x,i.x,r.y,i.y);
}
fn cmul(a:vec4f,b:vec4f,s:u32)->vec4f {
    let r=add(mul(a.xz,b.xz,s),-mul(a.yw,b.yw,s),s);
    let i=add(mul(a.xz,b.yw,s),mul(a.yw,b.xz,s),s);
    return vec4f(r.x,i.x,r.y,i.y);
}
)WGSL";
inline constexpr char scalar[] = R"WGSL(
fn cadd(a:vec4f,b:vec4f,s:u32)->vec4f { return vec4f(a.xy+b.xy,0.0,0.0); }
fn cmul(a:vec4f,b:vec4f,s:u32)->vec4f {
    return vec4f(a.x*b.x-a.y*b.y,a.x*b.y+a.y*b.x,0.0,0.0);
}
)WGSL";
}
