// Generated by scripts/embed.mjs; do not edit.
#pragma once
namespace webgpu_fft::detail {
inline constexpr char arithmetic[] = R"WGSL(
fn rnd(v:f32,s:u32)->f32 {
    atomicStore(&rounding[s],bitcast<u32>(v));
    return bitcast<f32>(atomicLoad(&rounding[s]));
}
fn norm(a:vec2f,s:u32)->vec2f {
    let h=rnd(a.x+a.y,s);let v=rnd(h-a.x,s);
    return vec2f(h,rnd(a.y-v,s));
}
fn add(a:vec2f,b:vec2f,s:u32)->vec2f {
    let h=rnd(a.x+b.x,s);let bv=rnd(h-a.x,s);let av=rnd(h-bv,s);
    let ae=rnd(a.x-av,s);let be=rnd(b.x-bv,s);
    let e=rnd(ae+be,s);let l=rnd(e+a.y,s);
    return norm(vec2f(h,rnd(l+b.y,s)),s);
}
fn mul(a:vec2f,b:vec2f,s:u32)->vec2f {
    let h=rnd(a.x*b.x,s);let e=rnd(fma(a.x,b.x,-h),s);
    let c0=rnd(a.x*b.y,s);let c1=rnd(a.y*b.x,s);
    return norm(vec2f(h,rnd(rnd(e+c0,s)+c1,s)),s);
}
)WGSL";
inline constexpr char paired[] = R"WGSL(
fn cadd(a:vec4f,b:vec4f,s:u32)->vec4f {
    let r=add(a.xz,b.xz,s);let i=add(a.yw,b.yw,s);
    return vec4f(r.x,i.x,r.y,i.y);
}
fn cmul(a:vec4f,b:vec4f,s:u32)->vec4f {
    let r=add(mul(a.xz,b.xz,s),-mul(a.yw,b.yw,s),s);
    let i=add(mul(a.xz,b.yw,s),mul(a.yw,b.xz,s),s);
    return vec4f(r.x,i.x,r.y,i.y);
}
)WGSL";
inline constexpr char scalar[] = R"WGSL(
fn cadd(a:vec4f,b:vec4f,s:u32)->vec4f { return vec4f(a.xy+b.xy,0.0,0.0); }
fn cmul(a:vec4f,b:vec4f,s:u32)->vec4f {
    return vec4f(a.x*b.x-a.y*b.y,a.x*b.y+a.y*b.x,0.0,0.0);
}
)WGSL";
inline constexpr char large[] = R"WGSL(
struct Params { n:u32, m:u32, batches:u32, span:u32, kind:u32, flags:u32, pad0:u32, pad1:u32 }
@group(0) @binding(0) var<storage,read> input:array<f32>;
@group(0) @binding(1) var<storage,read_write> output:array<f32>;
@group(0) @binding(2) var<storage,read> table:array<vec4f>;
@group(0) @binding(3) var<uniform> params:Params;
var<workgroup> rounding:array<atomic<u32>,64>;
fn load_complex(i:u32)->vec4f {
    return vec4f(input[4u*i],input[4u*i+1u],input[4u*i+2u],input[4u*i+3u]);
}
fn store_complex(i:u32,v:vec4f) {
    output[4u*i]=v.x;output[4u*i+1u]=v.y;output[4u*i+2u]=v.z;output[4u*i+3u]=v.w;
}
fn conjugate(v:vec4f)->vec4f { return vec4f(v.x,-v.y,v.z,-v.w); }
fn reverse_index(j:u32)->u32 { return reverseBits(j) >> (32u-firstLeadingBit(params.m)); }
fn flat_index(id:vec3u,groups:vec3u)->u32 { return id.x+id.y*groups.x*64u; }
@compute @workgroup_size(64)
fn pack(@builtin(global_invocation_id) id:vec3u,@builtin(num_workgroups) groups:vec3u,@builtin(local_invocation_index) lane:u32) {
    let i=flat_index(id,groups);if(i>=params.m*params.batches){return;}
    let batch=i/params.m;var j=i%params.m;if((params.flags&2u)!=0u){j=reverse_index(j);}
    var v=vec4f(0.0);
    if(j<params.n){
        if(params.kind==1u){let at=2u*(batch*params.n+j);v=vec4f(input[at],0.0,input[at+1u],0.0);}
        else if(params.kind==2u){
            let half=params.n/2u+1u;
            if(j<half){v=load_complex(batch*half+j);}else{v=conjugate(load_complex(batch*half+params.n-j));}
            if(j==0u || (params.n%2u==0u && j==params.n/2u)){v.y=0.0;v.w=0.0;}
        }else{v=load_complex(batch*params.n+j);}
        if((params.flags&4u)!=0u){v=cmul(v,table[params.m/2u+j],lane);}
    }
    store_complex(i,v);
}
@compute @workgroup_size(64)
fn butterfly(@builtin(global_invocation_id) id:vec3u,@builtin(num_workgroups) groups:vec3u,@builtin(local_invocation_index) lane:u32) {
    let i=flat_index(id,groups);if(i>=params.m*params.batches){return;}
    let j=i%params.m;let half=params.span/2u;let k=j%half;let base=i-j+(j/params.span)*params.span;
    var root=table[k*(params.m/params.span)];if((params.flags&1u)!=0u){root=conjugate(root);}
    let a=load_complex(base+k);var b=cmul(load_complex(base+k+half),root,lane);
    if(j%params.span>=half){b=-b;}store_complex(i,cadd(a,b,lane));
}
@compute @workgroup_size(64)
fn multiply(@builtin(global_invocation_id) id:vec3u,@builtin(num_workgroups) groups:vec3u,@builtin(local_invocation_index) lane:u32) {
    let i=flat_index(id,groups);if(i>=params.m*params.batches){return;}
    let j=reverse_index(i%params.m);
    store_complex(i,cmul(load_complex((i/params.m)*params.m+j),table[params.m/2u+params.n+j],lane));
}
@compute @workgroup_size(64)
fn unpack(@builtin(global_invocation_id) id:vec3u,@builtin(num_workgroups) groups:vec3u,@builtin(local_invocation_index) lane:u32) {
    let i=flat_index(id,groups);var width=params.n;if(params.kind==1u){width=params.n/2u+1u;}
    if(i>=width*params.batches){return;}let j=i%width;var v=load_complex((i/width)*params.m+j);
    if((params.flags&4u)!=0u){v=cmul(v,table[params.m/2u+j],lane);}
    v=cmul(v,table[arrayLength(&table)-1u],lane);
    if(params.kind==2u){output[2u*i]=v.x;output[2u*i+1u]=v.z;}
    else{
        if(params.kind==1u && (j==0u || (params.n%2u==0u && j==params.n/2u))){v.y=0.0;v.w=0.0;}
        store_complex(i,v);
    }
}
)WGSL";
inline constexpr char optimized[] = R"WGSL(
// Exact real scaling and axis rotations avoid zero terms in complex products.
// Paired operations still use the same explicit f32 rounding barriers.
fn cscale(a:vec4f,b:vec2f,s:u32)->vec4f {
    if(PAIRED){let r=mul(a.xz,b,s);let i=mul(a.yw,b,s);return vec4f(r.x,i.x,r.y,i.y);}
    return vec4f(a.xy*b.x,0.0,0.0);
}
fn rotate_i(a:vec4f)->vec4f {return vec4f(-a.y,a.x,-a.w,a.z);}
fn twiddle(a:vec4f,k:u32,s:u32)->vec4f {
    if(k==0u){return a;}
    if(N%2u==0u && k==N/2u){return -a;}
    if(N%4u==0u && k==N/4u){if(INVERSE){return rotate_i(a);}return -rotate_i(a);}
    if(N%4u==0u && k==3u*N/4u){if(INVERSE){return -rotate_i(a);}return rotate_i(a);}
    return cmul(a,roots[k],s);
}
fn radix_three(a:vec4f,b:vec4f,c:vec4f,q:u32,s:u32)->vec4f {
    let pair=cadd(b,c,s);
    if(q==0u){return cadd(a,pair,s);}
    let center=cadd(a,cscale(pair,vec2f(-0.5,0.0),s),s);
    var skew=rotate_i(cscale(cadd(b,-c,s),SQRT_THREE_OVER_TWO,s));
    if((q==1u)!=INVERSE){skew=-skew;}
    return cadd(center,skew,s);
}
)WGSL";
}
