// Mechanical generated-source update; WGSL numerical kernels live in shaders/.
import {readFileSync, writeFileSync} from 'node:fs';
const root = new URL('../', import.meta.url);
const parts = Object.fromEntries(['arithmetic', 'paired', 'scalar', 'large', 'optimized'].map(name =>
  [name, readFileSync(new URL(`shaders/${name}.wgsl`, root), 'utf8')]));
const outputs = {
  'src/source.js': '// Generated by scripts/embed.mjs; do not edit.\n' +
    Object.entries(parts).map(([name, text]) => `export const ${name} = ${JSON.stringify(text)};\n`).join(''),
  'include/webgpu_fft/source.hpp': '// Generated by scripts/embed.mjs; do not edit.\n#pragma once\nnamespace webgpu_fft::detail {\n' +
    Object.entries(parts).map(([name, text]) => `inline constexpr char ${name}[] = R"WGSL(\n${text})WGSL";\n`).join('') + '}\n',
};
for (const [path, text] of Object.entries(outputs)) {
  const url = new URL(path, root);
  if (process.argv.includes('--check')) {
    if (readFileSync(url, 'utf8') !== text) throw Error(`${path} is stale; run npm run generate`);
  } else writeFileSync(url, text);
}
